/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/Ubik/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/Ubik/share/locale\" -I. -I../lib -I../lib -O2 -Wall";
const char *link_string = "gcc -O2 -Wall -liconv -lgnutls -lgcrypt -lgpg-error -lz -lz -lpcre ftp-opie.o gnutls.o ../lib/libgnu.a";
